services:
  frontend:
    build:
      context: frontend
    ports:
      - "5173:5173"
    networks:
      - wecallnetwork
    volumes:
      - frontend_node_modules:/workspace/frontend/node_modules
      - .:/workspace

  backend:
    build:
      context: backend
    ports:
      - "3000:3000"
    networks:
      - wecallnetwork
    volumes:
      - backend_node_modules:/workspace/backend/node_modules
      - .:/workspace

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wecall
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - 3306:3306
    networks:
      - wecallnetwork

networks:
  wecallnetwork:
volumes:
  frontend_node_modules:
  backend_node_modules: