services:
  frontend:
    build:
      context: frontend
    ports:
      - "5173:5173"
    networks:
      - wecallnetwork
    volumes:
      - frontend_node_modules:/workspace/frontend/node_modules
      - .:/workspace
    env_file:
      - .env

  backend:
    build:
      context: backend
    ports:
      - "3000:3000"
    networks:
      - wecallnetwork
    volumes:
      - backend_node_modules:/workspace/backend/node_modules
      - .:/workspace
    environment:
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - wecallnetwork

networks:
  wecallnetwork:
volumes:
  frontend_node_modules:
  backend_node_modules: